# Generated by Django 5.2.10 on 2026-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_seats_booked_booking_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pnr',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
